PretrainedImageNet: false
arch: ''
batch_size: 16
epochs: 10
freeze_epochs: 0
frozen_lr: 5.0e-05
input_size: 256
loss: smooth
lr: 0.0003
model_ema_decay: 0.98
my_config: configs/config.yaml
num_classes: 2
num_workers: 4
optim: sgd
own_weights: weights/Classification/resnest101e/resnest101e_ema.pt
schedule: false
schedule_gamma: 0.5
schedule_step: 3
train_dir: data/Classification/tigers_vs_leopards/train
unfreeze: first
use_model_ema: true
val_dir: data/Classification/tigers_vs_leopards/val
